/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/partidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["partidos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partidos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["partido"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/encuestas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["encuestas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/congreso/composicion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["composicion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["calendario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Escanos: {
            nombre: string;
            /** Format: int32 */
            escanos: number;
        };
        Partido: {
            id: string | null;
            nombre: string;
            siglas: string | null;
            web: string | null;
            logo: string | null;
            /** Format: int32 */
            fundacion: number | null;
            color: string | null;
            /** Format: int32 */
            escanos: number | null;
            candidaturas: components["schemas"]["Escanos"][] | null;
            fuente: string | null;
        };
        RespuestaListPartido: {
            datos: components["schemas"]["Partido"][];
            /** Format: date-time */
            actualizado: string;
            desactualizado: boolean;
            fuente: string;
        };
        RespuestaPartido: {
            datos: components["schemas"]["Partido"];
            /** Format: date-time */
            actualizado: string;
            desactualizado: boolean;
            fuente: string;
        };
        Encuesta: {
            encuestadora: string;
            trabajoDeCampo: string;
            /** Format: date */
            fin: string;
            /** Format: int32 */
            muestra: number | null;
            estimaciones: components["schemas"]["Estimacion"][];
            enlace: string | null;
        };
        Encuestas: {
            partidos: string[];
            encuestas: components["schemas"]["Encuesta"][];
            fuente: string;
        };
        Estimacion: {
            partido: string;
            /** Format: double */
            voto: number | null;
            escanos: string | null;
        };
        RespuestaEncuestas: {
            datos: components["schemas"]["Encuestas"];
            /** Format: date-time */
            actualizado: string;
            desactualizado: boolean;
            fuente: string;
        };
        Composicion: {
            porFormacion: components["schemas"]["Escanos"][];
            porGrupo: components["schemas"]["Escanos"][];
            /** Format: int32 */
            total: number;
            fuente: string;
        };
        RespuestaComposicion: {
            datos: components["schemas"]["Composicion"];
            /** Format: date-time */
            actualizado: string;
            desactualizado: boolean;
            fuente: string;
        };
        Calendario: {
            /** Format: date */
            fechaElecciones: string;
            hitos: components["schemas"]["Hito"][];
            /** Format: date */
            vedaEncuestasDesde: string;
            encuestasPublicables: boolean;
        };
        Hito: {
            /** Format: date */
            fecha: string;
            titulo: string;
            fuente: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    partidos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaListPartido"];
                };
            };
        };
    };
    partido: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaPartido"];
                };
            };
        };
    };
    encuestas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaEncuestas"];
                };
            };
        };
    };
    composicion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RespuestaComposicion"];
                };
            };
        };
    };
    calendario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Calendario"];
                };
            };
        };
    };
}
